### ISSUE TITLE
Test cases covering uploads of duplicit file content

### ISSUE THREAD

**Issue by MichalPysik** [pulp/pulp_file#790]
This feature request is tied directly to issue #774. The tests need to account for the new feature.

Because of how this new feature works, the test called 'test_same_sha256_same_relative_path_not_allowed' which can be found inside 'pulp_file/tests/functional/api/test_crud_content_unit.py' is now redundant. It should be replaced by tests those make sure that:
- a duplicate filecontent can be "re-uploaded" when no repository is specified (admin only), in which case the pulp_href of the existing unit should be returned
- a duplicate filecontent unit can be "re-uploaded" into a different repository
- a duplicate filecontent unit can be re-uploaded into a repository already containing this unit, in which case the pulp_href of the existing unit should be returned

I propose two separate test scenarios:
1. Test without specifying repository - we make sure that admin can reupload content, which returns the existing pulp_href, and also that user cannot (this user-part fits more into rbac tests, but let's add it as a bonus)
2. Test with specified repository - users A/B create repositories A/B. User A tries to upload the same content to repository A twice, second attempt should return href of the existing content. User B should be able to re-upload the content to his repository without problems.
This test can be also done as admin (who creates both repos) without users, but I think the user scenario offer a little extra coverage, since admin has all the priviliges in the world and some edge-case might get dismissed because of that fact.

**Comment by mdellweg** [comment]
The tests must go with the feature. I don't think we need a separate issue (and changelog entry).

**Comment by MichalPysik** [comment]
> The tests must go with the feature. I don't think we need a separate issue (and changelog entry).

Ok, I will close this issue, squash the two commits and update the commit message.

**Comment by ipanova** [comment]
@mdellweg It was me who suggested to file a separate Test issue, where it will be space for outlining in the written way the test scenarios for the sake of practice and clarity.

**Comment by mdellweg** [comment]
Actually it would be a very nice idea to add acceptance criteria like that to a feature request.
In the end, I believe the feature and its tests must should come in the same PR and that closes one issue.
