### ISSUE TITLE
Migrate off of pulp-smash

### ISSUE THREAD

**Issue by bmbouter** [pulp/pulp_file#804]
As determined in [this discourse thread](https://discourse.pulpproject.org/t/retirement-of-pulp-smash/579/2) by the CI/CD mini-team, let's demonstrate one plugin entirely moving off of pulp-smash. pulp_file is a good candidate for that. To do this:

1. Move any necessary pytest fixtures from pulp-smash to pulpcore
2. Remove pulp-smash from the test dependencies
3. Ensure pulp-smash is not being installed at all in the CI either
4. Move any necessary utils functions

It would be good if whatever moves into pulpcore does not have the ability to reach "remote machines under test". 1) We don't want that anymore architecturally and 2) if we do that we have to also move the configuration for such machinery (which we don't want either).

**Comment by lubosmj** [comment]
Additional work is required to be done:

1. rewriting all tests to use pytest
https://github.com/pulp/pulp_file/pull/812#issuecomment-1254703848

2. moving additional utilities from pulp-smash to pulpcore and declaring no pulp-smash dependencies
https://github.com/pulp/pulpcore/pull/3223#issuecomment-1254709182

**Comment by mdellweg** [comment]
I know, this is a way smaller scope, but we could start to migrate pytest fixtures today. Maybe sort them in two buckets:
1. Bindings fixtures with a new way to generate the bindings_config
2. Supporting fixtures like the aiohttp server in a fixture

**Comment by lubosmj** [comment]
I am reviving this. We are ready to go!
