### ISSUE TITLE
Add option to hide PULP_MANIFEST

### ISSUE THREAD

**Issue by daviddavis** [pulp/pulp_file#837]
We have a request to publish some files and we want to use pulp_file. However, these repos won't be ingested by another pulp instance so we'd like to hide the PULP_MANIFEST file. 

I see two ways to do this:

1. Add a publish option to not create the pulp manifest file
2. Add an option (or setting?) that have the content app hide the PULP_MANIFEST file

**Comment by ipanova** [comment]
i am for 1

**Comment by dkliban** [comment]
Option 1 seems like the most reasonable one.

**Comment by mdellweg** [comment]
3. Option: A new plain publication type could just not publish the manifest.
4. Variation of option 1: Specifying None as the manifest path prevents creating it.

**Comment by ipanova** [comment]
@daviddavis will you be able to implement this RFE?

**Comment by daviddavis** [comment]
Sure, I went with option 4 that @mdellweg proposed.
