### ISSUE TITLE
Requesting pulp_file bindings release 1.11.z with updated faraday dependencies

### ISSUE THREAD

**Issue by sjha4** [pulp/pulp_file#841]
We are planning to upgrade to pulp_file_client 1.11.1 but it has faraday dependencies >= 0.17, < 1.9.0. This conflicts with other plugins being packaged which have faraday depency as >= 1.0.1, < 2.0.

**Comment by dkliban** [comment]
https://pypi.org/project/pulp-file-client/1.11.2/
https://rubygems.org/gems/pulp_file_client/versions/1.11.2/
